spring.application.name=restrocloud-api
# Server settings
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/restrocloud_api
spring.datasource.username=root
spring.datasource.password=Root@123


# JPA & Hibernate change --->spring.jpa.hibernate.ddl-auto=update  before deploying
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Error handling
server.error.include-message=never
server.error.include-binding-errors=never
server.error.whitelabel.enabled=false

